application:
  working-hours:
    monday: "13:00-18:00"
    tuesday: "09:00-18:00"
    wednesday: "09:00-18:00"
    thursday: "09:00-18:00"
    friday: "09:00-13:00"
  providers:
    openweather:
      base-url: "http://api.openweathermap.org"
      security:
        api-key: 481d417514a22de2a06e9982a4ce9e16
      forecasts:
        exclusions:
        - current
        - minutely
        - daily
        - alerts
        units: metric
