application:
  providers:
    openweather:
      base-url: "http://api.openweathermap.org"
      security:
        api-key: 481d417514a22de2a06e9982a4ce9e16
      forecasts:
        exclusions:
        - current
        - minutely
        - daily
        - alerts
        units: metric
